name: mpv clang

on:
  workflow_dispatch:
    inputs:
      pre_build_script:
        description: 'Optional shell command(s) to run before build'
        required: false
        type: string

defaults:
  run:
    shell: bash

jobs:
  build_mpv:
    name: Building mpv (x86_64)
    runs-on: ubuntu-latest

    container:
      image: docker://ghcr.io/shinchiro/archlinux:latest

    env:
      BIT: x86_64
      ARCH: x86_64

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: master

      - name: Setup git config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$PWD"

      - name: Restore clang sysroot cache
        uses: actions/cache/restore@v6
        with:
          path: clang_root
          key: ${{ secrets.CACHE_VERSION }}-clang_root-${{ github.run_id }}
          restore-keys: |
            ${{ secrets.CACHE_VERSION }}-clang_root

      - name: Restore repository cache
        uses: actions/cache/restore@v6
        with:
          path: src_packages
          key: ${{ secrets.CACHE_VERSION }}-repository-${{ github.run_id }}
          restore-keys: |
            ${{ secrets.CACHE_VERSION }}-repository

      - name: Restore build cache
        uses: actions/cache/restore@v6
        with:
          path: build_${{ env.BIT }}
          key: ${{ secrets.CACHE_VERSION }}-clang-${{ env.BIT }}_toolchain-${{ github.run_id }}
          restore-keys: |
            ${{ secrets.CACHE_VERSION }}-clang-${{ env.BIT }}_toolchain

      - name: Run custom pre-build script
        if: ${{ inputs.pre_build_script != '' }}
        env:
          PRE_BUILD_SCRIPT: ${{ inputs.pre_build_script }}
        run: |
          echo "Running custom pre-build script:"
          echo "$PRE_BUILD_SCRIPT"
          bash -euo pipefail -c "$PRE_BUILD_SCRIPT"

      - name: Configure CMake
        run: |
          cmake \
            -DTARGET_ARCH=$ARCH-w64-mingw32 \
            -DCOMPILER_TOOLCHAIN=clang \
            -DCMAKE_INSTALL_PREFIX=$PWD/clang_root \
            -DMINGW_INSTALL_PREFIX=$PWD/build_$BIT/$BIT-w64-mingw32 \
            -DSINGLE_SOURCE_LOCATION=$PWD/src_packages \
            -DRUSTUP_LOCATION=$PWD/clang_root/install_rustup \
            -DENABLE_CCACHE=ON \
            -DCLANG_PACKAGES_LTO=ON \
            -G Ninja \
            --fresh \
            -B build_$BIT \
            -S $PWD

          ninja -C build_$BIT download || true

      - name: Build mpv
        run: |
          ninja -C build_$BIT update
          ninja -C build_$BIT mpv-fullclean
          ninja -C build_$BIT mpv

      - name: Package mpv
        run: |
          mkdir -p release_$BIT
          ninja -C build_$BIT mpv-packaging
          mv build_$BIT/mpv*.7z release_$BIT/

      - name: Collect logs
        if: always()
        run: |
          mkdir -p build_${BIT}_logs

          find build_$BIT -type f \
            \( -iname "*-*.log" -o -path "*/ffbuild/config.log" \) \
            -exec cp --parents {} build_${BIT}_logs/ \; || true

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: mpv-${{ env.BIT }}-logs
          path: build_${{ env.BIT }}_logs
          retention-days: 1

      - name: Upload mpv
        uses: actions/upload-artifact@v7
        with:
          name: mpv-${{ env.BIT }}
          path: release_${{ env.BIT }}/mpv-x86_64-*.7z
          if-no-files-found: error

      - name: Upload libmpv
        uses: actions/upload-artifact@v7
        with:
          name: libmpv-x86_64
          path: release_${{ env.BIT }}/mpv-dev-x86_64-*.7z
          if-no-files-found: error

      - name: Clean mpv build
        if: always()
        run: |
          rm -rf build_$BIT/mpv*

      - name: Clean Rust cache
        if: always()
        run: |
          ninja -C build_$BIT cargo-clean || true

      - name: Save clang sysroot cache
        if: always()
        uses: actions/cache/save@v6
        with:
          path: clang_root
          key: ${{ secrets.CACHE_VERSION }}-clang_root-${{ github.run_id }}

      - name: Save repository cache
        if: always()
        uses: actions/cache/save@v6
        with:
          path: src_packages
          key: ${{ secrets.CACHE_VERSION }}-repository-${{ github.run_id }}

      - name: Save build cache
        if: always()
        uses: actions/cache/save@v6
        with:
          path: build_${{ env.BIT }}
          key: ${{ secrets.CACHE_VERSION }}-clang-${{ env.BIT }}_toolchain-${{ github.run_id }}
